import { config } from 'dotenv';
import { existsSync } from 'fs';
import path from 'path';
import { PrismaClient } from '../src/generated/prisma/client';
import { hashSync } from 'bcryptjs';

// Hard require .env.local — stress seed must never run against prod creds
const localPath = path.join(process.cwd(), '.env.local');
if (!existsSync(localPath)) {
  console.error('Refusing to run: .env.local not found.');
  console.error('  Stress seed only runs against a local DB you control.');
  console.error('  Copy .env.local.example to .env.local and fill in your local Postgres credentials.');
  process.exit(1);
}
config({ path: localPath, override: true });

function assertSafeTarget() {
  const url = process.env.DATABASE_URL ?? '';
  const masked = url.replace(/:\/\/[^@]+@/, '://***@');
  const isLocal =
    /@(localhost|127\.0\.0\.1|::1)[:/]/.test(url) ||
    /@host\.docker\.internal[:/]/.test(url);
  const forced = process.env.STRESS_ALLOW_REMOTE === '1';
  if (!url) {
    console.error('Refusing to run: DATABASE_URL is empty in .env.local');
    process.exit(1);
  }
  if (!isLocal && !forced) {
    console.error('Refusing to run: DATABASE_URL in .env.local is not a local host.');
    console.error(`  url: ${masked}`);
    console.error('  expected hostname: localhost / 127.0.0.1');
    console.error('  override: STRESS_ALLOW_REMOTE=1 npm run seed:stress');
    process.exit(1);
  }
  console.log(`Target: ${masked}`);
}

const prisma = new PrismaClient();

const ENTRY_COUNT = 500;
const DRIVER_COUNT = 6;
const DAY_COUNT = 3;

const STRESS_INVOICE_PREFIX = 'INV-STRESS-';
const STRESS_LIVESTOCK_PREFIX = 'MF-STRESS-';
const STRESS_DRIVER_PREFIX = 'stressdriver';

const ANCHORS: { name: string; lat: number; lng: number }[] = [
  { name: 'Jakarta Pusat', lat: -6.1751, lng: 106.865 },
  { name: 'Jakarta Selatan', lat: -6.2615, lng: 106.8106 },
  { name: 'Jakarta Barat', lat: -6.1683, lng: 106.7588 },
  { name: 'Jakarta Timur', lat: -6.2251, lng: 106.9004 },
  { name: 'Jakarta Utara', lat: -6.1214, lng: 106.8748 },
  { name: 'Bekasi', lat: -6.2383, lng: 106.9756 },
  { name: 'Tangerang', lat: -6.1781, lng: 106.6303 },
  { name: 'Tangerang Selatan', lat: -6.3019, lng: 106.652 },
  { name: 'Depok', lat: -6.4025, lng: 106.7942 },
  { name: 'Bogor', lat: -6.595, lng: 106.8166 },
];

const FIRST_NAMES = ['Pak', 'Bu', 'Haji', 'Hajjah', 'Bapak', 'Ibu'];
const NAMES = [
  'Surya', 'Dimas', 'Rizky', 'Andi', 'Bambang', 'Joko', 'Agus', 'Hendra',
  'Yusuf', 'Ahmad', 'Fajar', 'Rama', 'Adit', 'Wahyu', 'Eko', 'Budi',
  'Devi', 'Sari', 'Lina', 'Tini', 'Rina', 'Yuli', 'Mega', 'Putri',
  'Reza', 'Iwan', 'Hadi', 'Doni', 'Toni', 'Anton', 'Heri', 'Supri',
];

const SAMPLE_NOTES = [
  'Tolong sampai sebelum jam 9 pagi',
  'Pintu pagar warna biru, masuk ke dalam',
  'Hubungi dulu sebelum datang',
  'Taruh di depan garasi',
  'Antar ke kantor, bukan rumah',
  'Telepon 30 menit sebelum tiba',
  'Masuk gang kecil kanan pertigaan',
  'Rumah paling ujung, ada pohon mangga',
  'Jangan parkir di depan pagar',
  'Penerima atas nama istri',
];

const PENGIRIMAN_OPTIONS = [
  'HARI_H', 'HARI_H', 'HARI_H', 'HARI_H', // weighted — most are HARI_H
  'H_1', 'H_1',
  'H_2',
  'H_3',
  'TITIP_POTONG',
] as const;

const TYPES = ['KAMBING', 'DOMBA', 'SAPI'] as const;
const KAMBING_GRADES = ['SUPER', 'A', 'B', 'C', 'D'] as const;
const DOMBA_GRADES = ['A', 'B', 'C'] as const;

type LivestockSeed = {
  sku: string;
  type: (typeof TYPES)[number];
  grade: 'SUPER' | 'A' | 'B' | 'C' | 'D' | null;
  weightMin: number;
  weightMax: number;
  hargaJual: number;
  hargaModal: number;
  tag: string;
};

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function jitter(value: number, delta: number): number {
  return value + (Math.random() - 0.5) * 2 * delta;
}

function randomBuyer(idx: number) {
  const anchor = ANCHORS[idx % ANCHORS.length];
  const lat = jitter(anchor.lat, 0.05);
  const lng = jitter(anchor.lng, 0.05);
  const honor = pick(FIRST_NAMES);
  const name = pick(NAMES);
  const phone = `08${Math.floor(100000000 + Math.random() * 899999999)}`;
  return {
    name: `${honor} ${name} ${idx + 1}`,
    phone,
    address: `Jl. ${anchor.name} No. ${(idx % 99) + 1} Blok ${String.fromCharCode(65 + (idx % 26))}`,
    lat,
    lng,
    // Google Maps URL in the form generated by Google's "Share location" button
    maps: `https://www.google.com/maps?q=${lat.toFixed(6)},${lng.toFixed(6)}`,
  };
}

function buildLivestock(): LivestockSeed[] {
  const out: LivestockSeed[] = [];
  for (let i = 0; i < ENTRY_COUNT; i++) {
    const type = pick(TYPES);
    let grade: LivestockSeed['grade'] = null;
    let weight = 0;
    let hargaJual = 0;
    let hargaModal = 0;

    if (type === 'KAMBING') {
      grade = pick(KAMBING_GRADES);
      weight = 25 + Math.floor(Math.random() * 25);
      const prices: Record<(typeof KAMBING_GRADES)[number], [number, number]> = {
        SUPER: [4000000, 5000000],
        A: [3500000, 4400000],
        B: [2700000, 3800000],
        C: [2300000, 3300000],
        D: [1700000, 2350000],
      };
      [hargaModal, hargaJual] = prices[grade];
    } else if (type === 'DOMBA') {
      grade = pick(DOMBA_GRADES);
      weight = 25 + Math.floor(Math.random() * 25);
      const prices: Record<(typeof DOMBA_GRADES)[number], [number, number]> = {
        A: [3200000, 4000000],
        B: [2500000, 3400000],
        C: [2000000, 2800000],
      };
      [hargaModal, hargaJual] = prices[grade];
    } else {
      weight = 250 + Math.floor(Math.random() * 150);
      hargaModal = 18000000 + Math.floor(Math.random() * 5000000);
      hargaJual = hargaModal + 3000000 + Math.floor(Math.random() * 2000000);
    }

    const sku = `${STRESS_LIVESTOCK_PREFIX}${String(i + 1).padStart(4, '0')}`;
    out.push({
      sku,
      type,
      grade,
      weightMin: weight,
      weightMax: weight,
      hargaJual,
      hargaModal,
      tag: `STRESS-${String(i + 1).padStart(4, '0')}`,
    });
  }
  return out;
}

async function cleanup() {
  console.log('Cleaning up previous stress data...');
  const e = await prisma.entry.deleteMany({
    where: { invoiceNo: { startsWith: STRESS_INVOICE_PREFIX } },
  });
  const l = await prisma.livestock.deleteMany({
    where: { sku: { startsWith: STRESS_LIVESTOCK_PREFIX } },
  });
  const d = await prisma.profile.deleteMany({
    where: { username: { startsWith: STRESS_DRIVER_PREFIX } },
  });
  console.log(`  removed ${e.count} entries, ${l.count} livestock, ${d.count} drivers`);
}

async function main() {
  assertSafeTarget();
  await cleanup();

  console.log(`Creating ${DRIVER_COUNT} stress drivers...`);
  const driverPasswordHash = hashSync('driver', 10);
  await prisma.profile.createMany({
    data: Array.from({ length: DRIVER_COUNT }, (_, i) => ({
      username: `${STRESS_DRIVER_PREFIX}${i + 1}`,
      password: driverPasswordHash,
      name: `Driver Stress ${i + 1}`,
      role: 'DRIVER' as const,
      phone: `0813${String(10000000 + i).padStart(8, '0')}`,
      vehiclePlate: `B ${1000 + i} STR`,
    })),
  });
  const drivers = await prisma.profile.findMany({
    where: { username: { startsWith: STRESS_DRIVER_PREFIX } },
    orderBy: { username: 'asc' },
  });

  console.log(`Creating driver availability for ${DAY_COUNT} days...`);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const dates = Array.from({ length: DAY_COUNT }, (_, i) => {
    const d = new Date(today);
    d.setDate(today.getDate() + i);
    return d;
  });
  await prisma.driverAvailability.createMany({
    data: drivers.flatMap((d) =>
      dates.map((date) => ({ driverId: d.id, date, isActive: true })),
    ),
    skipDuplicates: true,
  });

  let sales = await prisma.profile.findFirst({ where: { role: 'SALES' } });
  if (!sales) {
    sales = await prisma.profile.create({
      data: {
        username: 'sales',
        password: hashSync('sales', 10),
        name: 'Sales MF',
        role: 'SALES',
        phone: '08111111111',
      },
    });
  }
  let admin = await prisma.profile.findFirst({
    where: { role: { in: ['ADMIN', 'SUPER_ADMIN'] } },
  });
  if (!admin) {
    admin = await prisma.profile.create({
      data: {
        username: 'admin',
        password: hashSync('admin', 10),
        name: 'Admin MF',
        role: 'ADMIN',
        phone: '08123456789',
      },
    });
  }

  console.log(`Creating ${ENTRY_COUNT} livestock...`);
  const livestockSeeds = buildLivestock();
  await prisma.livestock.createMany({ data: livestockSeeds });
  const livestockRows = await prisma.livestock.findMany({
    where: { sku: { startsWith: STRESS_LIVESTOCK_PREFIX } },
    select: { id: true, sku: true, hargaJual: true, hargaModal: true },
    orderBy: { sku: 'asc' },
  });

  console.log(`Creating ${ENTRY_COUNT} entries with deliveries...`);
  const approvedAt = new Date();
  let created = 0;

  for (let i = 0; i < livestockRows.length; i++) {
    const lv = livestockRows[i];
    const buyer = randomBuyer(i);
    const deliveryDate = dates[i % DAY_COUNT];
    const invoiceNo = `${STRESS_INVOICE_PREFIX}${String(i + 1).padStart(4, '0')}`;

    const hargaJual = lv.hargaJual ?? 0;
    const hargaModal = lv.hargaModal ?? 0;
    const resellerCut = Math.floor(Math.random() * 4) * 50000;
    const hpp = hargaModal + resellerCut;
    const profit = hargaJual - hpp;

    const paymentRoll = Math.random();
    const paymentStatus =
      paymentRoll < 0.6 ? 'LUNAS' : paymentRoll < 0.9 ? 'DP' : 'BELUM_BAYAR';
    const dp = paymentStatus === 'DP' ? Math.floor(hargaJual * 0.4) : null;
    const totalBayar = paymentStatus === 'LUNAS' ? hargaJual : dp;

    const pengiriman = pick(PENGIRIMAN_OPTIONS);
    const notes = Math.random() < 0.3 ? pick(SAMPLE_NOTES) : null;
    const buktiTransfer =
      paymentStatus === 'LUNAS'
        ? ['/uploads/transfers/sample-receipt-1.jpg', '/uploads/transfers/sample-receipt-2.jpg']
        : paymentStatus === 'DP'
          ? ['/uploads/transfers/sample-receipt-1.jpg']
          : [];

    await prisma.entry.create({
      data: {
        invoiceNo,
        salesId: sales.id,
        status: 'APPROVED',
        approvedAt,
        approvedBy: admin.id,
        paymentStatus,
        dp,
        totalBayar,
        buyerName: buyer.name,
        buyerPhone: buyer.phone,
        buyerAddress: buyer.address,
        buyerMaps: buyer.maps,
        buyerLat: buyer.lat,
        buyerLng: buyer.lng,
        pengiriman,
        notes,
        buktiTransfer,
        isSent: false,
        deliveryDate,
        items: {
          create: [
            {
              livestockId: lv.id,
              hargaJual,
              hargaModal,
              resellerCut,
              hpp,
              profit,
            },
          ],
        },
        delivery: {
          create: { status: 'PENDING' },
        },
      },
    });

    created += 1;
    if (created % 50 === 0) {
      console.log(`  ${created}/${ENTRY_COUNT}`);
    }
  }

  await prisma.livestock.updateMany({
    where: { sku: { startsWith: STRESS_LIVESTOCK_PREFIX } },
    data: { isSold: true },
  });

  console.log('');
  console.log('Stress seed complete.');
  console.log(`  ${DRIVER_COUNT} drivers  → login: ${STRESS_DRIVER_PREFIX}1..${DRIVER_COUNT}  password: driver`);
  console.log(`  ${DAY_COUNT} delivery days starting ${dates[0].toISOString().slice(0, 10)}`);
  console.log(`  ${ENTRY_COUNT} APPROVED entries — all fields populated, PENDING deliveries (unassigned)`);
  console.log('');
  console.log('Next: open /admin/deliveries → Generate Routes to exercise TSP.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
